services:
  api:
    image: wildflower-api
    build: .
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/wildflower

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
