services:
  api:
    image: wildflower-api
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
    # env_file:
    #   - ./backend/.env
    volumes:
      - ./backend/src:/app/src
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/wildflower
    # - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}

  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  # test:
  #   image: wildflower-api #use same image as api
  #   depends_on:
  #     - api
  #   volumes:
  #     - ./backend/src/index.js:/app/src/index.js
  #   command: node src/index.js
